# https://taskfile.dev
# https://github.com/mdouchement/checksum

version: '3'

vars:
  VERSION: 0.2.5
  REVISION: { sh: git rev-parse HEAD }

env:
  GO111MODULE: on
  CGO_ENABLED: 0

tasks:
  clean:
    desc: Clean project
    cmds:
      - rm -rf ./dist

  build-all:
    desc: Build all binaries
    cmds:
      - task: clean
      - mkdir -p ./dist

      # Supported dist:    go tool dist list
      - |
        pairs=(linux/amd64 linux/arm linux/arm64 darwin/arm64 darwin/amd64)

        for pair in "${pairs[@]}"
        do
          os="${pair%/*}"
          arch="${pair#*/}"

          env GOOS=${os} GOARCH=${arch} go build -ldflags "{{.LDFLAGS | splitList "\n" | join " "}}" -o ./dist/seikan-${os}-${arch} ./cmd/seikan
          ( cd ./dist && checksum --algs="sha256" --append-to checksum.txt seikan-${os}-${arch} )
        done
      - |
        pairs=(windows/amd64)

        for pair in "${pairs[@]}"
        do
          os="${pair%/*}"
          arch="${pair#*/}"

          env GOOS=${os} GOARCH=${arch} go build -ldflags "{{.LDFLAGS | splitList "\n" | join " "}}" -o ./dist/seikan-${os}-${arch}.exe ./cmd/seikan
          ( cd ./dist && checksum --algs="sha256" --append-to checksum.txt seikan-${os}-${arch}.exe )
        done
    vars:
      LDFLAGS: |
        -s
        -w
        -X main.version={{.VERSION}}
        -X main.revision={{ printf "%.7s" .REVISION }}
        -X main.date={{now | date "2006-01-02~15:04:05"}}
